version: "3.3"
services:
    threadbot:
        restart: always
        build:
            context: ./threadbot
        environment:
            - NODE_ENV=production
    webserver:
        restart: always
        network_mode: "host"
        depends_on:
            - bot
        build:
            context: ./webServer
        environment:
            - NODE_ENV=production
    bot:
        restart: always
        network_mode: "host"
        build:
            context: ./bot
        environment:
            - NODE_ENV=production
    nginx:
        restart: "no"
        restart: always
        restart: on-failure
        restart: unless-stopped
        tty: true
        network_mode: "host"
        depends_on: 
            - webserver
            - bot
        build:
            context: ./nginx