version: "3.3"
services:
    webserver:
        restart: always
        network_mode: host
        depends_on:
            - bot
        build:
            context: ./webServer
        ports:
            - "8080:8080/tcp"
            - "8080:8080/udp"
            - "443:443/tcp"
            - "443:443/udp"
            - "80:80/tcp"
            - "80:80/udp"
        environment:
            - NODE_ENV=production
    game_server:
        restart: always
        network_mode: host
        depends_on:
            - bot
            - webserver
        build:
            context: ./gameServer
        ports:
            - "8081:8081/tcp"
            - "8081:8081/udp"
            - "443:443/tcp"
            - "443:443/udp"
            - "80:80/tcp"
            - "80:80/udp"
        environment:
            - NODE_ENV=production
    bot:
        restart: always
        network_mode: host
        build:
            context: ./bot
        ports:
            - "9000:9000/tcp"
            - "9000:9000/udp"
        environment:
            - NODE_ENV=production
    nginx:
        restart: "no"
        restart: always
        restart: on-failure
        restart: unless-stopped
        tty: true
        network_mode: host
        depends_on: 
            - webserver
            - game_server
            - bot
        build:
            context: ./nginx
        ports:
            - "80:80/tcp"
            - "80:80/udp"
            - "443:443/tcp"
            - "443:443/udp"