version: "3.8"
services:
    webserver:
        depends_on:
            - bot
        build:
            context: ./webServer
            network: host
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=production
    bot:
        build:
            context: ./bot
            network: host
        ports:
            - "9000:9000"
        environment:
            - NODE_ENV=production
    nginx:
        restart: always
        depends_on: 
            - webserver
            - bot
        build:
            context: ./nginx
            network: host
        ports:
            - "80:80"
            - "443:443"