version: "3.3"
services:
    webserver:
        restart: always
        network_mode: bridge
        depends_on:
            - core_bot
        build:
            context: ./webServer
        ports:
            - "8080:8080/tcp"
            - "8080:8080/udp"
            - "443:443/tcp"
            - "443:443/udp"
            - "80:80/tcp"
            - "80:80/udp"
        environment:
            - NODE_ENV=production
    core_bot:
        restart: always
        network_mode: bridge
        build:
            context: ./coreBot
        ports:
            - "9000:9000/tcp"
            - "9000:9000/udp"
        environment:
            - NODE_ENV=production
    nginx:
        restart: unless-stopped
        network_mode: bridge
        depends_on: 
            - webserver
            - bot
        build:
            context: ./nginx
        ports:
            - "80:80/tcp"
            - "80:80/udp"
            - "443:443/tcp"
            - "443:443/udp"