import * as React from 'react';
import { Card } from '../components';

const CookiePolicy = () => {
    return (
        <div className="layout cookie-policy">
            <div className="flex flex-center">
                <Card colour="primary">
                    <h3 className="text-center">Cookie Policy</h3>
                    <p className="text-bold">Stormcloud Services uses cookies to provide its services.</p>
                    <p className="text-bold">What Are Cookies</p>
                    <p>
                        As is common practice with almost all professional websites this site uses cookies, which are
                        tiny files that are downloaded to your computer, to improve your experience.
                        This page describes what information they gather, how we use it and why we sometimes need to
                        store these cookies.
                        We will also share how you can prevent these cookies from being stored however this may
                        downgrade or 'break' certain elements of the sites functionality.
                    </p>
                    <p>For more general information on cookies see the Wikipedia article on HTTP Cookies.</p>
                    <p className="text-bold">How We Use Cookies</p>
                    <p>
                        We use cookies for a variety of reasons detailed below. Unfortunately in most cases there are no
                        industry standard options for disabling cookies without completely disabling the functionality
                        and features they add to this site.
                        It is recommended that you leave on all cookies if you are not sure whether you need them or not
                        in case they are used to provide a service that you use.
                    </p>
                    <p className="text-bold">Disabling Cookies</p>
                    <p>
                        You can prevent the setting of cookies by adjusting the settings on your browser (see your
                        browser Help for how to do this). Be aware that disabling cookies will affect the functionality
                        of this and many other websites that you visit.
                        Disabling cookies will usually result in also disabling certain functionality and features of
                        the this site. Therefore it is recommended that you do not disable cookies.
                    </p>
                    <p className="text-bold">The Cookies We Set</p>
                    <p>Account related cookies</p>
                    <p className="text-bold">Forms related cookies</p>
                    <p>
                        When you submit data to through a form such as those found on application forms, etc on the site
                        cookies may be set to remember your user details for future correspondence.
                    </p>
                    <p className="text-bold">Login related cookies</p>
                    <p>
                        We use cookies when you are logged in so that we can remember this fact. This prevents you from
                        having to log in every single time you visit a new page.
                        These cookies are typically removed or cleared when you log out to ensure that you can only
                        access restricted features and areas when logged in.
                        This cookie in the case of StormCloud Services is set by discord since we use them to verify
                        that you are a member of Stormcloud as well as getting your
                        username for content generated by you.
                    </p>
                    <p className="text-bold">Third Party Cookies</p>
                    <p>
                        In some special cases we also use cookies provided by trusted third parties.The following
                        section details which third party cookies you might encounter through this site.
                    </p>
                    <p>
                        This site uses Cloudflare Cookies since they are the provider of our DNS and DDoS protection
                        they require cookies to be set that allow them to verify you are a genuine user
                        and not a bot part of an attack towards our servers.
                    </p>
                    <p>
                        Hopefully that has clarified things for you and as was previously mentioned if there is
                        something that you aren't sure whether you need or not it's usually safer to leave cookies
                        enabled in case it does interact with one of the features you use on our site.
                    </p>
                    <p>
                        However if you are still looking for more information then you can contact us through one of our
                        preferred contact methods:
                    </p>
                    <a href="https://discord.gg/Vnrb6scBHG">Click to join our Discord Server and ask an Admin</a>
                    <p>Developer's Discord Account: 𝕵𝖆𝖘𝖕𝖊𝖗#5992 | Discord User ID: 217387293571284992</p>
                    <p></p>
                </Card>
            </div>
        </div>
    );
}

export default CookiePolicy;